using Bolt.Automation.ApiClients.GetQuoteApi.Models.Applicant;
using Bolt.Automation.Common.Utils;
using Bolt.Automation.TestDataProvider.TestData.CommonTestData;

namespace Bolt.Automation.TestDataProvider.TestData.ApplicantTestData
{
    public static partial class ApplicantTestData
    {
        public static class Applicants
        {
            // Change from static readonly to property - generates new instance each time.
            // On Staging uses real names generated by Bogus via NameSelector.
            public static ApplicantRequestModel RandomApplicant => new()
            {
                FirstName = NameSelector.GetFirstName(),
                LastName = NameSelector.GetLastName(),
                Email = "test" + RandomManager.GetRandomString(5) + "@test.com",
                Addresses = [AddressData.TX],
                PhoneNumbers = [PhoneNumbers.numbers],
            };

            public static ApplicantRequestModel RandomApplicantUpdate => new()
            {
                FirstName = NameSelector.GetFirstName(),
                LastName = NameSelector.GetLastName(),
                Email = "testUpdate" + RandomManager.GetRandomString(6) + "@test.com",
                Addresses = [AddressData.NY_Averill_Park],
                PhoneNumbers = [PhoneNumbers.NumberUpdate],
            };

            public static readonly ApplicantRequestModel USAAApplicant = new()
            {
                FirstName = "UsaaAuto",
                LastName = "Boilt",
                Email = "test@test.com",
                Addresses = [AddressData.IL],
                PhoneNumbers = [PhoneNumbers.numbers],
                Ids = [Ids.ids]
            };
        }
    }
}
