//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Bolt.Automation.ApiClients.SSO.Saml.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Bolt.Automation.ApiClients.SSO.Saml.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;s:Envelope xmlns:s=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///	&lt;s:Body&gt;
        ///&lt;UpdateAppointments xmlns=&quot;http://tempuri.org/&quot;&gt;
        ///	&lt;request xmlns:a=&quot;http://schemas.datacontract.org/2004/07/SaisToBoltService.Entities.ServiceContracts&quot; xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///		&lt;a:Carriers&gt;
        ///			&lt;a:DirectCarriers&gt;
        ///				&lt;a:CarrierInfo&gt;
        ///					&lt;a:Carrier&gt;Progressive&lt;/a:Carrier&gt;
        ///					&lt;a:Lobs&gt;
        ///						&lt;a:LobInfo&gt;
        ///							&lt;a:Lob&gt;PersonalAuto&lt;/a:Lob&gt;
        ///							&lt;a:StatesInfo&gt;
        ///								&lt;a:StatesInfo&gt;
        ///									 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string direct_template {
            get {
                return ResourceManager.GetString("direct_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;s:Envelope xmlns:s=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///	&lt;s:Body&gt;
        ///		&lt;UpdateAppointments xmlns=&quot;http://tempuri.org/&quot;&gt;
        ///			&lt;request xmlns:a=&quot;http://schemas.datacontract.org/2004/07/SaisToBoltService.Entities.ServiceContracts&quot; xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///				&lt;a:Carriers&gt;
        ///					&lt;a:DirectCarriers i:nil=&quot;true&quot;/&gt;
        ///					&lt;a:RestrictedCarriers&gt;
        ///						&lt;a:CarrierInfo&gt;
        ///							&lt;a:Carrier&gt;Clearcover&lt;/a:Carrier&gt;
        ///							&lt;a:Lobs&gt;
        ///								&lt;a:LobInfo&gt;
        ///									&lt;a:Lob&gt;PersonalAuto&lt;/a:Lo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RemoveProgressiveAutoRestricted_template {
            get {
                return ResourceManager.GetString("RemoveProgressiveAutoRestricted_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;s:Envelope xmlns:s=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///	&lt;s:Body&gt;
        ///		&lt;UpdateAppointments xmlns=&quot;http://tempuri.org/&quot;&gt;
        ///			&lt;request xmlns:a=&quot;http://schemas.datacontract.org/2004/07/SaisToBoltService.Entities.ServiceContracts&quot; xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///				&lt;a:Carriers&gt;
        ///					&lt;a:DirectCarriers&gt;
        ///						&lt;a:CarrierInfo&gt;
        ///							&lt;a:Carrier&gt;Progressive&lt;/a:Carrier&gt;
        ///							&lt;a:Lobs&gt;
        ///								&lt;a:LobInfo&gt;
        ///									&lt;a:Lob&gt;PersonalAuto&lt;/a:Lob&gt;
        ///									&lt;a:StatesInfo&gt;
        ///										&lt;a: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RemoveSafecoAutoDirect_template {
            get {
                return ResourceManager.GetString("RemoveSafecoAutoDirect_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;s:Envelope xmlns:s=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///	&lt;s:Body&gt;
        ///		&lt;UpdateAppointments xmlns=&quot;http://tempuri.org/&quot;&gt;
        ///			&lt;request xmlns:a=&quot;http://schemas.datacontract.org/2004/07/SaisToBoltService.Entities.ServiceContracts&quot; xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///				&lt;a:Carriers&gt;
        ///					&lt;a:DirectCarriers i:nil=&quot;true&quot;/&gt;
        ///					&lt;a:RestrictedCarriers&gt;
        ///						&lt;a:CarrierInfo&gt;
        ///							&lt;a:Carrier&gt;Progressive&lt;/a:Carrier&gt;
        ///							&lt;a:Lobs&gt;
        ///								&lt;a:LobInfo&gt;
        ///									&lt;a:Lob&gt;PersonalAuto&lt;/a:L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string restricted_template {
            get {
                return ResourceManager.GetString("restricted_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;samlp:Response xmlns:saml=&quot;urn:oasis:names:tc:SAML:2.0:assertion&quot; xmlns:samlp=&quot;urn:oasis:names:tc:SAML:2.0:protocol&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; Destination=&quot;&quot; ID=&quot;&quot; IssueInstant=&quot;&quot; Version=&quot;2.0&quot;&gt;
        ///	&lt;saml:Issuer Format=&quot;urn:oasis:names:tc:SAML:2.0:nameid-format:entity&quot;&gt;&lt;/saml:Issuer&gt;
        ///	&lt;samlp:Status&gt;
        ///		&lt;samlp:StatusCode Value=&quot;urn:oasis:names:tc:SAML:2.0:status:Success&quot;/&gt;
        ///	&lt;/samlp:Status&gt;
        ///	&lt;saml:Assertion ID=&quot;&quot; IssueInstant=&quot;&quot; Version [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SaisSamlResponseTemplateGetCarrierCredentials {
            get {
                return ResourceManager.GetString("SaisSamlResponseTemplateGetCarrierCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;samlp:Response xmlns:saml=&quot;urn:oasis:names:tc:SAML:2.0:assertion&quot; xmlns:samlp=&quot;urn:oasis:names:tc:SAML:2.0:protocol&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; Destination=&quot;&quot; ID=&quot;&quot; IssueInstant=&quot;&quot; Version=&quot;2.0&quot;&gt;
        ///  &lt;saml:Issuer Format=&quot;urn:oasis:names:tc:SAML:2.0:nameid-format:entity&quot;&gt;&lt;/saml:Issuer&gt;
        ///  &lt;samlp:Status&gt;
        ///    &lt;samlp:StatusCode Value=&quot;urn:oasis:names:tc:SAML:2.0:status:Success&quot;&gt;&lt;/samlp:StatusCode&gt;
        ///  &lt;/samlp:Status&gt;
        ///  &lt;saml:Assertion ID=&quot;&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Saml2ResponseTemplate {
            get {
                return ResourceManager.GetString("Saml2ResponseTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;samlp:Response xmlns:saml=&quot;urn:oasis:names:tc:SAML:2.0:assertion&quot; xmlns:samlp=&quot;urn:oasis:names:tc:SAML:2.0:protocol&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; Destination=&quot;&quot; ID=&quot;&quot; IssueInstant=&quot;&quot; Version=&quot;2.0&quot;&gt;
        ///  &lt;saml:Issuer Format=&quot;urn:oasis:names:tc:SAML:2.0:nameid-format:entity&quot;&gt;&lt;/saml:Issuer&gt;
        ///  &lt;samlp:Status&gt;
        ///    &lt;samlp:StatusCode Value=&quot;urn:oasis:names:tc:SAML:2.0:status:Success&quot;&gt;&lt;/samlp:StatusCode&gt;
        ///  &lt;/samlp:Status&gt;
        ///  &lt;saml:Assertion ID=&quot;&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Saml2ResponseTemplateWithGroupExternalId {
            get {
                return ResourceManager.GetString("Saml2ResponseTemplateWithGroupExternalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;samlp:Response xmlns:saml=&quot;urn:oasis:names:tc:SAML:2.0:assertion&quot; xmlns:samlp=&quot;urn:oasis:names:tc:SAML:2.0:protocol&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; Destination=&quot;&quot; ID=&quot;&quot; IssueInstant=&quot;&quot; Version=&quot;2.0&quot;&gt;
        ///&lt;saml:Issuer Format=&quot;urn:oasis:names:tc:SAML:2.0:nameid-format:entity&quot;/&gt;
        ///&lt;samlp:Status&gt;
        ///&lt;samlp:StatusCode Value=&quot;urn:oasis:names:tc:SAML:2.0:status:Success&quot;/&gt;
        ///&lt;/samlp:Status&gt;
        ///&lt;saml:Assertion ID=&quot;&quot; IssueInstant=&quot;&quot; Version=&quot;2.0&quot;&gt;
        ///&lt;saml:Issu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SamlPartnerPortal {
            get {
                return ResourceManager.GetString("SamlPartnerPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html xmlns=&quot;https://www.w3.org/1999/xhtml&quot;&gt; 
        ///    &lt;head&gt;
        ///        &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;/&gt;
        ///        &lt;title&gt;SAML 2.0 POST response&lt;/title&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///        &lt;!--form method=&quot;post&quot; action=&quot;https://allstate.test.boltinsurance.com/SingleSignOn/SSO&quot;--&gt;
        ///        &lt;form method=&quot;post&quot; action=&quot;@action@&quot;&gt;
        ///        &lt;div&gt;                     
        ///            &lt;input type=&quot;hidden&quot; name=&quot;RelayState&quot; value=&quot;RelayStateData&quot; /&gt;
        ///            &lt;input type=&quot;hidden&quot; name=&quot;S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SamlTemplate {
            get {
                return ResourceManager.GetString("SamlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Bolt Test Page&lt;/title&gt;
        ///
        ///    &lt;style&gt;
        ///        #dev {
        ///            border-radius: 25px;
        ///            border: 2px solid RED;
        ///            padding: 20px;
        ///            width: 200px;
        ///            height: 90px;
        ///        }
        ///
        ///        #liberty {
        ///            border-radius: 25px;
        ///            border: 2px solid #73AD21;
        ///            padding: 20px;
        ///            width: 200px;
        ///            height: 30 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test_html {
            get {
                return ResourceManager.GetString("test_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;s:Envelope xmlns:s=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///	
        ///&lt;s:Body&gt;
        ///&lt;UpdateAppointments xmlns=&quot;http://tempuri.org/&quot;&gt;
        ///  &lt;request xmlns:a=&quot;http://schemas.datacontract.org/2004/07/SaisToBoltService.Entities.ServiceContracts&quot; xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///    &lt;a:Carriers&gt;
        ///      &lt;a:DirectCarriers i:nil=&quot;true&quot;&gt;&lt;/a:DirectCarriers&gt;
        ///      &lt;a:RestrictedCarriers i:nil=&quot;true&quot;&gt;&lt;/a:RestrictedCarriers&gt;
        ///      &lt;a:UnappointedCarriers&gt;
        ///        &lt;a:CarrierInfo&gt;
        ///          &lt;a:Carrier&gt;Safec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Unappointed_template {
            get {
                return ResourceManager.GetString("Unappointed_template", resourceCulture);
            }
        }
    }
}
