<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LaunchDarkly.ServerSdk" />
    <PackageReference Include="Microsoft.Graph" />
    <PackageReference Include="Microsoft.Identity.Client" />
    <PackageReference Include="Refit" />
    <PackageReference Include="Refit.HttpClientFactory" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Automation.Configuration\Automation.Configuration.csproj" />
    <ProjectReference Include="..\Bolt.Automation.Common\Bolt.Automation.Common.csproj" />
  </ItemGroup>

</Project>
