using System.Text;

namespace Bolt.Automation.AgentTools.Code;

public sealed record WipStopResult(
    bool Ok,
    string? CommitSha,
    string? Branch,
    string? ResumeNotePath,
    int FilesStaged,
    string? Message);

/// <summary>
/// Codifies the strategic-pause pattern: stage everything, commit with a
/// <c>WIP-STOP:</c> subject, and drop a RESUME-NOTE.md at the repo root so the
/// next session (or the user) has the context to pick back up.
/// </summary>
internal sealed class WipStop
{
    private const string ResumeNoteName = "RESUME-NOTE.md";

    private readonly string _repoRoot;
    public WipStop(string repoRoot) => _repoRoot = repoRoot;

    public WipStopResult Run(string note, string timestampUtc)
    {
        var branch = Git("rev-parse", "--abbrev-ref", "HEAD")?.Trim();

        // Count what's about to be staged (porcelain lines) for the report.
        var statusBefore = Git("status", "--porcelain") ?? string.Empty;
        var filesStaged = statusBefore.Split('\n', StringSplitOptions.RemoveEmptyEntries).Length;

        if (filesStaged == 0)
            return new WipStopResult(false, null, branch, null, 0,
                "Nothing to commit — working tree is clean.");

        var add = RunGit(["add", "-A"]);
        if (add.ExitCode != 0)
            return new WipStopResult(false, null, branch, null, filesStaged,
                $"git add failed: {add.StdErr.Trim()}");

        var subject = $"WIP-STOP: {note}";
        var commit = RunGit(["commit", "-m", subject]);
        if (commit.ExitCode != 0)
            return new WipStopResult(false, null, branch, null, filesStaged,
                $"git commit failed: {commit.StdErr.Trim()}{commit.StdOut.Trim()}");

        var sha = Git("rev-parse", "HEAD")?.Trim();

        // Write the resume note AFTER committing — it points at the WIP commit.
        var notePath = Path.Combine(_repoRoot, ResumeNoteName);
        File.WriteAllText(notePath, BuildNote(note, branch, sha, timestampUtc, statusBefore));

        return new WipStopResult(true, sha, branch, notePath, filesStaged, null);
    }

    private static string BuildNote(string note, string? branch, string? sha, string timestampUtc, string stagedStatus)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# RESUME NOTE");
        sb.AppendLine();
        sb.AppendLine($"> Generated by `nexus-agent code wip-stop` at {timestampUtc}.");
        sb.AppendLine();
        sb.AppendLine($"- **Branch:** `{branch ?? "(unknown)"}`");
        sb.AppendLine($"- **WIP commit:** `{sha ?? "(unknown)"}`");
        sb.AppendLine();
        sb.AppendLine("## Note");
        sb.AppendLine();
        sb.AppendLine(note);
        sb.AppendLine();
        sb.AppendLine("## To resume");
        sb.AppendLine();
        sb.AppendLine("```bash");
        sb.AppendLine("# Inspect the WIP commit, then continue. To un-stage the WIP commit but keep changes:");
        sb.AppendLine($"git reset --soft HEAD~1   # if HEAD is still the WIP-STOP commit");
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("## Working tree at stop time");
        sb.AppendLine();
        sb.AppendLine("```");
        sb.Append(stagedStatus.TrimEnd());
        sb.AppendLine();
        sb.AppendLine("```");
        return sb.ToString();
    }

    private string? Git(params string[] args)
    {
        var r = RunGit(args);
        return r.ExitCode == 0 ? r.StdOut : null;
    }

    private ProcessResult RunGit(string[] args)
    {
        var full = new List<string> { "-C", _repoRoot };
        full.AddRange(args);
        return ProcessRunner.Run("git", full, _repoRoot, 30_000);
    }
}
