<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>


  <ItemGroup>
    <None Update="..\Bolt.Automation.InternalServices\Database\Configs\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Bolt.Microservice.Consumer.Interfaces" />
    <PackageReference Include="Bolt.Microservice.Cryptography.Interfaces" />
    <PackageReference Include="Bolt.Microservice.Quote.Interfaces" />
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Playwright" />
    <PackageReference Include="Refit.HttpClientFactory" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bolt.Automation.Core\Bolt.Automation.Core.csproj" />
    <ProjectReference Include="..\Bolt.Automation.ExternalServices\Bolt.Automation.ExternalServices.csproj" />
    <ProjectReference Include="..\Bolt.Automation.TestDataProvider\Bolt.Automation.TestDataProvider.csproj" />
    <ProjectReference Include="..\Bolt.Automation.ApiClients\Bolt.Automation.ApiClients.csproj" />
    <ProjectReference Include="..\Bolt.Automation.Common\Bolt.Automation.Common.csproj" />
    <ProjectReference Include="..\Bolt.Automation.FrontEnds\Bolt.Automation.FrontEnds.csproj" />
    <ProjectReference Include="..\Bolt.Automation.Tests\Bolt.Automation.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.QA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.UAT.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="local.runsettings">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

	</Project>