// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using LinqToDB.Mapping;


namespace Bolt.Automation.InternalServices.Database.Entities.Main
{
	[Table("Consumer")]
	public class Consumer
	{
		[Column("Id"                 , IsPrimaryKey = true )] public Guid     Id                  { get; set; } // uniqueidentifier
		[Column("Email"                                    )] public string?  Email               { get; set; } // varchar(60)
		[Column("Password"           , CanBeNull    = false)] public string   Password            { get; set; } = null!; // nvarchar(1000)
		[Column("PasswordExpiration"                       )] public DateTime PasswordExpiration  { get; set; } // datetime
		[Column("DateCreated"                              )] public DateTime DateCreated         { get; set; } // datetime
		[Column("Status"                                   )] public short    Status              { get; set; } // smallint
		[Column("IsActive"                                 )] public bool     IsActive            { get; set; } // bit
		[Column("VerficationQuestion"                      )] public string?  VerficationQuestion { get; set; } // nvarchar(100)
		[Column("VerificationAnswer"                       )] public string?  VerificationAnswer  { get; set; } // nvarchar(100)
		[Column("FirstName"                                )] public string?  FirstName           { get; set; } // nvarchar(50)
		[Column("LastName"                                 )] public string?  LastName            { get; set; } // nvarchar(50)
		[Column("JobTitle"                                 )] public string?  JobTitle            { get; set; } // nvarchar(50)
		[Column("JobTitleOther"                            )] public string?  JobTitleOther       { get; set; } // nvarchar(50)
		[Column("BusinessTitle"                            )] public string?  BusinessTitle       { get; set; } // nvarchar(60)
		[Column("Agreed"                                   )] public bool?    Agreed              { get; set; } // bit
		[Column("Type"                                     )] public short    Type                { get; set; } // smallint
		[Column("Line"                                     )] public short    Line                { get; set; } // smallint
		[Column("MiddleName"                               )] public string?  MiddleName          { get; set; } // nvarchar(50)
		[Column("RecieveEmailStatus"                       )] public short    RecieveEmailStatus  { get; set; } // smallint
		[Column("ConsumerData"                             )] public string?  ConsumerData        { get; set; } // xml
		[Column("DateUpdated"                              )] public DateTime DateUpdated         { get; set; } // datetime
		[Column("Partner"                                  )] public short    Partner             { get; set; } // smallint
		[Column("GroupId"                                  )] public Guid?    GroupId             { get; set; } // uniqueidentifier
		[Column("SourceMedia"                              )] public short    SourceMedia         { get; set; } // smallint
		[Column("SourceKeyword"                            )] public string?  SourceKeyword       { get; set; } // nvarchar(50)
		[Column("ExternalId"                               )] public string?  ExternalId          { get; set; } // varchar(14)
		[Column("Tenant"             , CanBeNull    = false)] public string   Tenant              { get; set; } = null!; // varchar(100)
		[Column("CreatedByGroupId"                         )] public Guid?    CreatedByGroupId    { get; set; } // uniqueidentifier
		[Column("OwnedByGroupId"                           )] public Guid?    OwnedByGroupId      { get; set; } // uniqueidentifier
		[Column("CreatedByUserId"                          )] public Guid?    CreatedByUserId     { get; set; } // uniqueidentifier
		[Column("AssignedToUserId"                         )] public Guid?    AssignedToUserId    { get; set; } // uniqueidentifier
		[Column("UpdatedByUserId"                          )] public Guid?    UpdatedByUserId     { get; set; } // uniqueidentifier

		// #region Associations
		// /// <summary>
		// /// FK_AgentLastConsumer_ConsumerId_Consumer backreference
		// /// </summary>
		// [Association(ThisKey = nameof(Id), OtherKey = nameof(AgentLastConsumer.ConsumerId))]
		// public IEnumerable<AgentLastConsumer> AgentLastConsumers { get; set; } = null!;
		//
		// /// <summary>
		// /// FK_Consumer_GroupId_Group
		// /// </summary>
		// [Association(ThisKey = nameof(GroupId), OtherKey = nameof(Group.Id))]
		// public Group? Group { get; set; }
		//
		// /// <summary>
		// /// FK_ConsumerAgent_ConsumerId_Consumer backreference
		// /// </summary>
		// [Association(ThisKey = nameof(Id), OtherKey = nameof(ConsumerAgent.ConsumerId))]
		// public IEnumerable<ConsumerAgent> ConsumerAgents { get; set; } = null!;
		//
		// /// <summary>
		// /// FK_ConsumerAttachment_ConsumerId_Consumer backreference
		// /// </summary>
		// [Association(ThisKey = nameof(Id), OtherKey = nameof(ConsumerAttachment.ConsumerId))]
		// public IEnumerable<ConsumerAttachment> ConsumerAttachments { get; set; } = null!;
		//
		// /// <summary>
		// /// FK_ConsumerComment_ConsumerId_Consumer backreference
		// /// </summary>
		// [Association(ThisKey = nameof(Id), OtherKey = nameof(ConsumerComment.ConsumerId))]
		// public IEnumerable<ConsumerComment> ConsumerComments { get; set; } = null!;
		//
		// /// <summary>
		// /// FK_ConsumerConversation_ConsumerId_Consumer backreference
		// /// </summary>
		// [Association(ThisKey = nameof(Id), OtherKey = nameof(ConsumerConversation.ConsumerId))]
		// public IEnumerable<ConsumerConversation> ConsumerConversations { get; set; } = null!;
		//
		// /// <summary>
		// /// FK_ConsumerCryptoInfo_ConsumerId_Consumer backreference
		// /// </summary>
		// [Association(ThisKey = nameof(Id), OtherKey = nameof(DataModel.ConsumerCryptoInfo.ConsumerId))]
		// public ConsumerCryptoInfo? ConsumerCryptoInfo { get; set; }
		//
		// /// <summary>
		// /// FK_ConsumerFailedLoginInfo_ConsumerId_Consumer backreference
		// /// </summary>
		// [Association(ThisKey = nameof(Id), OtherKey = nameof(DataModel.ConsumerFailedLoginInfo.ConsumerId))]
		// public ConsumerFailedLoginInfo? ConsumerFailedLoginInfo { get; set; }
		//
		// /// <summary>
		// /// FK_ConsumerIndex_ConsumerId_Consumer backreference
		// /// </summary>
		// [Association(ThisKey = nameof(Id), OtherKey = nameof(DataModel.ConsumerIndex.ConsumerId))]
		// public ConsumerIndex? ConsumerIndex { get; set; }
		//
		// /// <summary>
		// /// FK_ConsumerLock_ConsumerId_Consumer backreference
		// /// </summary>
		// [Association(ThisKey = nameof(Id), OtherKey = nameof(DataModel.ConsumerLock.ConsumerId))]
		// public ConsumerLock? ConsumerLock { get; set; }
		//
		// /// <summary>
		// /// FK_ConsumerPasswordHistory_ConsumerId_Consumer backreference
		// /// </summary>
		// [Association(ThisKey = nameof(Id), OtherKey = nameof(ConsumerPasswordHistory.ConsumerId))]
		// public IEnumerable<ConsumerPasswordHistory> ConsumerPasswordHistories { get; set; } = null!;
		//
		// /// <summary>
		// /// FK_ConsumerProduct_ConsumerId_Consumer backreference
		// /// </summary>
		// [Association(ThisKey = nameof(Id), OtherKey = nameof(ConsumerProduct.ConsumerId))]
		// public IEnumerable<ConsumerProduct> ConsumerProducts { get; set; } = null!;
		//
		// /// <summary>
		// /// FK_ConsumerSearchHash_ConsumerId_Consumer backreference
		// /// </summary>
		// [Association(ThisKey = nameof(Id), OtherKey = nameof(ConsumerSearchHash.ConsumerId))]
		// public IEnumerable<ConsumerSearchHash> ConsumerSearchHashes { get; set; } = null!;
		//
		// /// <summary>
		// /// FK_DoublePositiveResult_ConsumerId_Consumer backreference
		// /// </summary>
		// [Association(ThisKey = nameof(Id), OtherKey = nameof(DataModel.DoublePositiveResult.ConsumerId))]
		// public DoublePositiveResult? DoublePositiveResult { get; set; }
		//
		// /// <summary>
		// /// FK_Policy_ConsumerId_Consumer backreference
		// /// </summary>
		// [Association(ThisKey = nameof(Id), OtherKey = nameof(Policy.ConsumerId))]
		// public IEnumerable<Policy> Policies { get; set; } = null!;
		//
		// /// <summary>
		// /// FK_PolicyLink_ConsumerId_Consumer backreference
		// /// </summary>
		// [Association(ThisKey = nameof(Id), OtherKey = nameof(PolicyLink.ConsumerId))]
		// public IEnumerable<PolicyLink> PolicyLinks { get; set; } = null!;
		//
		// /// <summary>
		// /// FK_ReferralConsumer_ConsumerId_Consumer backreference
		// /// </summary>
		// [Association(ThisKey = nameof(Id), OtherKey = nameof(ReferralConsumer.ConsumerId))]
		// public IEnumerable<ReferralConsumer> ReferralConsumers { get; set; } = null!;
		//
		// /// <summary>
		// /// FK_ScheduleACall_ConsumerId_Consumer backreference
		// /// </summary>
		// [Association(ThisKey = nameof(Id), OtherKey = nameof(ScheduleACall.ConsumerId))]
		// public IEnumerable<ScheduleACall> ScheduleACalls { get; set; } = null!;
		// #endregion
	}
}
