// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------
using System;
using LinqToDB.Mapping;

namespace Bolt.Automation.InternalServices.Database.Entities.Main
{
	[Table("Deeplink")]
	public class Deeplink
	{
		[Column("Id"               , IsPrimaryKey = true )] public Guid      Id                { get; set; } // uniqueidentifier
		[Column("Token"            , CanBeNull    = false)] public string    Token             { get; set; } = null!; // nvarchar(50)
		[Column("Data"                                   )] public string?   Data              { get; set; } // nvarchar(max)
		[Column("DateCreated"                            )] public DateTime  DateCreated       { get; set; } // datetime
		[Column("DateExpired"                            )] public DateTime  DateExpired       { get; set; } // datetime
		[Column("ContextId"                              )] public string?   ContextId         { get; set; } // nvarchar(200)
		[Column("IsValid"                                )] public bool      IsValid           { get; set; } // bit
		[Column("RenewalExpiryDate"                      )] public DateTime? RenewalExpiryDate { get; set; } // datetime
	}
}
