// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using LinqToDB.Mapping;

namespace Bolt.Automation.InternalServices.Database.Entities.Main
{
	[Table("EmailTemplate")]
	public class EmailTemplate
	{
		[Column("Id"          , IsPrimaryKey = true )] public Guid     Id           { get; set; } // uniqueidentifier
		[Column("TemplateType"                      )] public int      TemplateType { get; set; } // int
		[Column("Name"        , CanBeNull    = false)] public string   Name         { get; set; } = null!; // nvarchar(100)
		[Column("TemplateData", CanBeNull    = false)] public string   TemplateData { get; set; } = null!; // xml
		[Column("DateCreated"                       )] public DateTime DateCreated  { get; set; } // datetime
		[Column("IsActive"                          )] public bool     IsActive     { get; set; } // bit
		[Column("AgentId"                           )] public Guid     AgentId      { get; set; } // uniqueidentifier
		[Column("GroupId"                           )] public Guid     GroupId      { get; set; } // uniqueidentifier
		[Column("IsPublic"                          )] public bool     IsPublic     { get; set; } // bit
		[Column("IsDefault"                         )] public bool     IsDefault    { get; set; } // bit

		// #region Associations
		// /// <summary>
		// /// FK_EmailTemplatePromoImage_EmailTemplateId_EmailTemplate backreference
		// /// </summary>
		// [Association(ThisKey = nameof(Id), OtherKey = nameof(EmailTemplatePromoImage.EmailTemplateId))]
		// public IEnumerable<EmailTemplatePromoImage> EmailTemplatePromoImages { get; set; } = null!;
		// #endregion
	}
}
