// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------
using System;
using LinqToDB.Mapping;

namespace Bolt.Automation.InternalServices.Database.Entities.Main
{
	[Table("GroupRestrictions")]
	public class GroupRestrictions
	{
		[Column("GroupId"                                 )] public Guid     GroupId             { get; set; } // uniqueidentifier
		[Column("RestrictionType"                         )] public int      RestrictionType     { get; set; } // int
		[Column("CarrierRestrictions"                     )] public string?  CarrierRestrictions { get; set; } // xml
		[Column("AllowedCarriers"                         )] public string?  AllowedCarriers     { get; set; } // xml
		[Column("UserId"                                  )] public Guid?    UserId              { get; set; } // uniqueidentifier
		[Column("Id"                 , IsPrimaryKey = true)] public Guid     Id                  { get; set; } // uniqueidentifier
		[Column("DateCreated"                             )] public DateTime DateCreated         { get; set; } // datetime
		[Column("DateUpdated"                             )] public DateTime DateUpdated         { get; set; } // datetime

		// #region Associations
		// /// <summary>
		// /// FK_GroupRestrictions_GroupId_Group
		// /// </summary>
		// [Association(CanBeNull = false, ThisKey = nameof(GroupId), OtherKey = nameof(DataModel.Group.Id))]
		// public Group Group { get; set; } = null!;
		// #endregion
	}
}
